[package]
name = "swffgdice"
version = "0.1.0"
authors = ["Michael Stein <mstein@insanefactory.com>"]
edition = "2018"

[[bin]]
name = "swffgdice"
path = "src/main.rs"

[lib]
path = "src/lib/mod.rs"
crate-type = ["lib"] # "staticlib"

[dependencies]
rand = "0.8.3"
regex = "0.1.45"
