[package]
name = "swffgdice"
version = "0.1.0"
authors = ["Michael Stein <mstein@insanefactory.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
regex = "0.1.45"
